version: '2'
services:
    node:
        build: node/.
        command: node server
        volumes:
            - ./node:/node
            - /node/node_modules
        restart: always
        networks:
            - nginx_default
    reactjs:
        build: reactjs/.
        command: http-server ./build/. -p 80
        #ports:
        #    - "8001:80"
        volumes:
            - ./reactjs:/reactjs
            - ./reactjs/node_modules:/reactjs/node_modules
            - ./reactjs/build:/reactjs/build
        restart: always
        networks:
            - nginx_default

networks:
    nginx_default:
        external: true
